language: go
go:
- "1.13.x"
- "1.14.x"
install:
- MOD=`grep '^module ' go.mod | awk '{print $NF}'`
- DIR=`pwd`
- mkdir tools
- cd tools
- go mod init ${MOD}/tools
- go install golang.org/x/tools/cmd/goimports
- go install golang.org/x/lint/golint
- go install github.com/mattn/goveralls
- cd ${DIR}
script:
- make CI=true
- $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
