language: go
go:
- "1.13.x"
install:
- go get -u -v golang.org/x/tools/cmd/goimports
- go get -u -v golang.org/x/lint/golint
- go get -u -v github.com/mattn/goveralls
script:
- make CI=true
- $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
